# Generated by Django 3.1.4 on 2021-01-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evelyhone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rcandidate',
            new_name='Rcandidates',
        ),
    ]
